actors:
  mofumofu:
    image_url: /images/actors/nekochan.jpg
    name: mofumofu
    url: https://twitter.com/froakie0021
author: mofumofu
description: ひよこなもふちゃんは技術の本がすき
description_long: ひよこ（≒初心者）エンジニアな人の話と技術書の話をもふもふちゃんがねこちゃんに向かってするPodcast
email: froakie002@gmail.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag: hiyokoMofufm
itunes_podcast_url: https://itunes.apple.com/jp/podcast/%E3%81%B2%E3%82%88%E3%81%93%E3%81%AA%E3%82%82%E3%81%B5%E3%82%82%E3%81%B5%E3%81%A1%E3%82%83%E3%82%93%E3%81%A8%E6%8A%80%E8%A1%93%E5%90%8C%E4%BA%BA%E8%AA%8C-fm/id1387286295?l=en
keywords: 技術同人誌,技術書,ひよこエンジニア
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: ひよこなもふもふちゃんと技術同人誌.fm
url: https://mofumofu2.github.io/hiyokoMofu-fm/
